### ISSUE TITLE
multiline tooltip

### ISSUE THREAD

**Issue by brucou** [JonDum/ractive-tooltip#1]
I loved this decorator for ractive. I was wondering however how to have the tooltip display multilines text. I tried with \n but that did not work out. Many thanks!

**Comment by sarendipitee** [comment]
By default it has a [`white-space: nowrap`](https://github.com/JonDum/ractive-tooltip/blob/master/src/styles.styl#L12) style applied to the tooltip. Override that in your own styles and add a desired width to get a wrapping effect.
